import React, { useEffect, useState } from 'react';
import Head from 'next/head'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'

import ReactDOM from 'react-dom';

// components
import card from '@/components/card'


export default function Home() {


  // first block fetch
  const [data, setData] = useState([]);

    useEffect(() => {
        fetch('https://fakestoreapi.com/products')
            .then((res) => res.json())
            .then((data) => setData(data))
            .catch((error) => console.error(error));
    }, []);


  return (
    <>
    card data={data}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        HELLO WORLD!

        {/* <Link href="/about">About</Link> */}
      </main>
    </>
  )
}

ReactDOM.render(<Home />, document.getElementById('root'));


