import Head from "next/head";
import Link from "next/link";
import styles from "@/styles/Home.module.css";
// import components
import Card from "@/components/card";
import RegistrationForm from '@/components/registration';

export default function Home() {
  const data = [
    { title: "Name", description: "Restoran #1" },
    { title: "Adress", description: "Super street 3" },
    { title: "Rate", description: "5 stars" },
    { title: "Type of kitchen", description: "Italian" },
    { title: "Foto of restaurante", description: "Lorem5" },
  ];

    // registration 
    const App = () => {
      const handleRegister = (data: any) => {
          console.log(data);
      };
  
      return (
          <div>
              <h1>Registration</h1>
              <RegistrationForm onRegister={handleRegister} />
          </div>
      );
  };
  

  // const server = new Server();
  // // states
  // const [number, setNumber] = useState<number>(0);
  // // const [name, setName] = useState<string>("");
  // let [user, setUser] = useState<User>({
  //   name: "test",
  //   mail: "test",
  //   comment: "test",
  // });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Task 1
       
        {data.map((e: any) => {
          return <Card data={e} key={e} />;
        })}

        Task 3
        <App></App>

      </main>
    </>
  );
}